services:
  - type: web
    name: pdf-chat-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GROQ_API_KEY
        sync: false
      - key: HUGGINGFACEHUB_API_KEY
        sync: false
      - key: REDIS_URL
        sync: false
      - key: QDRANT_URL
        sync: false

  - type: worker
    name: pdf-worker
    env: node
    buildCommand: npm install
    startCommand: npm run worker
    envVars:
      - key: NODE_ENV
        value: production
      - key: HUGGINGFACEHUB_API_KEY
        sync: false
      - key: REDIS_URL
        sync: false
      - key: QDRANT_URL
        sync: false